# Generated by Django 4.2 on 2023-04-12 10:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('highlights', models.CharField(blank=True, max_length=100, null=True)),
                ('enddate', models.DateField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('startdate', models.DateField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.basics')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Work',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skills_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.basics')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projects_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('startdate', models.DateField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.basics')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profiles_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('network', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.basics')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('countrycode', models.CharField(max_length=100)),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.basics')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('languages_id', models.AutoField(primary_key=True, serialize=False)),
                ('fluency', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(max_length=100)),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.basics')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('studytype', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(max_length=100)),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('courses', models.CharField(blank=True, max_length=100, null=True)),
                ('enddate', models.DateField(blank=True, max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, max_length=100, null=True)),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.basics')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certificates_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('startdate', models.DateField(blank=True, max_length=100, null=True)),
                ('issuer', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.basics')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
